version: "3.9"

services:
  api:
    build: .
    container_name: taura_backend_api
    env_file:
      - .env
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py

  tests:
      build: .
      container_name: taura_backend_tests
      command: pytest -v
      volumes:
        - .:/app
      environment:
        - DATABASE_URL=sqlite:///data/test.db
        - OPENAI_API_KEY=${OPENAI_API_KEY}