version: "3.9"

services:
  api:
    build: .
    container_name: taura_backend_api
    command: python3 run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
